### PR TITLE
Add option to debounce scroll/resize events

### LINKED ISSUE #15: Debounce event listeners
Would you consider option to debounce scroll and resize event listeners?

Use case: lazy loaded images, user scrolls really fast up and down, but you only want to run callback when they actually stop (e.g. 300ms debounce).

### PR DESCRIPTION
**Pull request by niksy**
Closes #15.

Should we inline external dependancy (as Rollup does now) or make it as real CommonJS/ESM dependancy inside final bundle?

One other question: what do you think about decoupling external dependancy from library, so others can use their own throttle/debounce function? We could make callback which has one argument (handler for scroll/resize listener) and that callback should return wrapped handler. This way you could have option to easily add throttling instead of debouncing.

Or is this too much for this option?

E.g.

```js
{
  scrollResizeEvent: ( handler ) => {
    return debounce(300, handler);
  }
}
```

### CODE REVIEW

**Comment by gpoitch** [comment]
@niksy thanks for the PR.  I'd prefer your suggestion to bring your own debouncing function and keep this dependency free.

**Comment by niksy** [comment]
@gpoitch PR updated!

**Comment by gpoitch** [comment]
@niksy thanks, api looks good!

Unfortunately, I think we're going to have to rearchitect a bit.  This is an option on individual observers, but it's being applied to any observer that happens to be within the same viewport (e.g. window)

**Comment by niksy** [comment]
@gpoitch oh, I see now :( I don’t see how we can differentiate different handlers only by function, and adding function description (or ID) somehow seems hacky :(

**Pull request closed without merging**
